# Generated by Django 3.2.9 on 2021-12-20 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LinkkunApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='owner',
        ),
        migrations.AddField(
            model_name='link',
            name='cred',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
